### ISSUE TITLE
Wrong classes being downloaded?

### ISSUE THREAD

**Issue by brechmos-stsci** [mf1024/ImageNet-Datasets-Downloader#1]
I like the idea of this type of downloader and was going to try it out. So, I wanted to do 2 classes, hornet and wasp.  But I can't seem to find the correct set of parameters to download just those two.

For example:
```
python ./downloader.py -data_root ../../ --use_class_list true -class_list n02213543 n02213107 -images_per_class 500
Picked the following clases:
['sea boat', 'pavlova', 'corn', 'tank', 'army officer', 'record player', 'monk', 'lovebird', 'loom', 'shark']
Scraping images for class "sea boat"
```
I am not sure why it is showing 10 or so other classes that were not selected.  

Am I using the parameters incorrectly?

**Comment by mf1024** [comment]
Hello, 
before "use_class_list" argument you have two minus signs instead of one. 

This should work:
`python ./downloader.py -data_root ../../ -use_class_list true -class_list n02213543 n02213107 -images_per_class 500`
